### ISSUE TITLE
Polars Dataframe Serializer only supports Polars < 1.0

### ISSUE THREAD

**Issue by josiahschuller** [InfluxCommunity/influxdb3-python#106]
### Specifications

* Client Version: 0.6.1
* InfluxDB Version: 3
* Platform: Debian Linux
* Polars version: 1.2.1

### Code sample to reproduce problem

```python
import polars as pl
from influxdb_client_3 import InfluxDBClient3
client = InfluxDBClient3(host="host", token="token", org="org")
df = pl.DataFrame({
    "time": ["2024-08-01 00:00:00", "2024-08-01 01:00:00"],
    "temperature": [22.4, 21.8],
})
client.write(
    database="database",
    record=df,
    data_frame_measurement_name="measurement",
    data_frame_timestamp_column="time",
)
```

### Expected behavior

There should not be any errors.

### Actual behavior

```
2024-08-12 15:04:16 Traceback (most recent call last):
2024-08-12 15:04:16   File "/app/python_poc/data_ingestion.py", line 278, in <module>
2024-08-12 15:04:16     ingest_data(
2024-08-12 15:04:16   File "/app/python_poc/data_ingestion.py", line 216, in ingest_data
2024-08-12 15:04:16     db_interface.insert_data(df=df_formatted, file_name=file_name)
2024-08-12 15:04:16   File "/app/python_poc/database_interface.py", line 166, in insert_data
2024-08-12 15:04:16     client.write(
2024-08-12 15:04:16   File "/usr/local/lib/python3.12/site-packages/influxdb_client_3/__init__.py", line 165, in write
2024-08-12 15:04:16     self._write_api.write(bucket=database, record=record, **kwargs)
2024-08-12 15:04:16   File "/usr/local/lib/python3.12/site-packages/influxdb_client_3/write_client/client/write_api.py", line 370, in write
2024-08-12 15:04:16     self._serialize(record, write_precision, payloads, **kwargs)
2024-08-12 15:04:16   File "/usr/local/lib/python3.12/site-packages/influxdb_client_3/write_client/client/_base.py", line 253, in _serialize
2024-08-12 15:04:16     self._serialize(serializer.serialize(), write_precision, payload, **kwargs)
2024-08-12 15:04:16                     ^^^^^^^^^^^^^^^^^^^^^^
2024-08-12 15:04:16   File "/usr/local/lib/python3.12/site-packages/influxdb_client_3/write_client/client/write/dataframe_serializer.py", line 411, in serialize
2024-08-12 15:04:16     line_protocol_expr = chunk.apply(self.to_line_protocol, return_dtype=pl.Object)
2024-08-12 15:04:16                          ^^^^^^^^^^^
2024-08-12 15:04:16 AttributeError: 'DataFrame' object has no attribute 'apply'
```

### Additional info

According to the [Polars docs](https://docs.pola.rs/api/python/version/0.20/reference/dataframe/api/polars.DataFrame.apply.html), the `polars.DataFrame.apply` function was deprecated (due to being replaced by `polars.DataFrame.map_rows`). It has then been removed in version 1 of polars.

The Polars serializer uses the `polars.DataFrame.apply` function and thus does not work with polars >= 1

**Comment by bednar** [comment]
This is already fixed in https://github.com/InfluxCommunity/influxdb3-python/pull/99
