### ISSUE TITLE
`.write()` error when `org=` isn't set for the client

### ISSUE THREAD

**Issue by jstirnaman** [InfluxCommunity/influxdb3-python#38]
Expected: It works when passing `org=''`, but v3 client shouldn't require the `org` argument.

Build tested: 0.1.8, 0.1.9

Steps to reproduce:

1. Instantiate a client without passing the `org=` kwarg.
   ```py
   influxdb_downsampled = InfluxDBClient3(
    host=os.getenv('INFLUX_HOSTNAME'),
    token=os.getenv('INFLUX_READ_WRITE_TOKEN'),
    database=os.getenv('INFLUX_BUCKET')
   )
   ```
2. Call `client.write()`.
    ```py
    influxdb_downsampled.write(
    record=data_frame,
    data_frame_measurement_name="home_ds",
    data_frame_timestamp_column="time",
    data_frame_tag_columns=['room']
   )
    ```

Result:

```sh
Traceback (most recent call last):
  File "/Users/ja/Documents/GitHub/influxdb-api-examples/python/v3/downsample_influxql.py", line 36, in <module>
    influxdb_downsampled.write(
  File "/Users/ja/Documents/GitHub/influxdb-api-examples/python/conda-envs/env1/lib/python3.11/site-packages/influxdb_client_3/__init__.py", line 82, in write
    self._write_api.write(bucket=database, record=record, **kwargs)
  File "/Users/ja/Documents/GitHub/influxdb-api-examples/python/conda-envs/env1/lib/python3.11/site-packages/influxdb_client/client/write_api.py", line 378, in write
    results = list(map(write_payload, payloads.items()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ja/Documents/GitHub/influxdb-api-examples/python/conda-envs/env1/lib/python3.11/site-packages/influxdb_client/client/write_api.py", line 376, in write_payload
    return self._post_write(_async_req, bucket, org, final_string, payload[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ja/Documents/GitHub/influxdb-api-examples/python/conda-envs/env1/lib/python3.11/site-packages/influxdb_client/client/write_api.py", line 509, in _post_write
    return self._write_service.post_write(org=org, bucket=bucket, body=body, precision=precision,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ja/Documents/GitHub/influxdb-api-examples/python/conda-envs/env1/lib/python3.11/site-packages/influxdb_client/service/write_service.py", line 60, in post_write
    (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ja/Documents/GitHub/influxdb-api-examples/python/conda-envs/env1/lib/python3.11/site-packages/influxdb_client/service/write_service.py", line 88, in post_write_with_http_info
    self._post_write_prepare(org, bucket, body, **kwargs)
  File "/Users/ja/Documents/GitHub/influxdb-api-examples/python/conda-envs/env1/lib/python3.11/site-packages/influxdb_client/service/write_service.py", line 156, in _post_write_prepare
    raise ValueError("Missing the required parameter `org` when calling `post_write`")  # noqa: E501
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Missing the required parameter `org` when calling `post_write`
```

**Comment by jstirnaman** [comment]
My bad - the [README](https://github.com/InfluxCommunity/influxdb3-python#initialization) does still specify that `org` is required for Serverless. Is there a reason to not make it optional?

**Comment by Jayclifford345** [comment]
@ivankudibal what do you think about this? How have we handled this with the other client libs? For now, I will handle it by making the flag optional but just wondering about the writer's rewrite.

**Comment by bednar** [comment]
@Jayclifford345, in our other client libraries, `org` is set as an optional parameter.

**Comment by Jayclifford345** [comment]
Sweet I will do the same
