### ISSUE TITLE
Trying to run a small example project from the Examples and fails wih TypeError: TypeError: influxdb_client_3.write_client.client.influxdb_client.InfluxDBClient() got multiple values for keyword argument 'url'

### ISSUE THREAD

**Issue by lombaardcj** [InfluxCommunity/influxdb3-python#83]
### Please direct all support questions to slack or the forums. Thank you.

I want to test the new influxdb3-python client libary.

I watched the intro video `https://www.youtube.com/watch?v=tpdONTm1GC8` and I got stuck on a Windows 11 machine.

Steps to reproduce:
1) Activate venv
2) `pip install influxdb3-python`
3) create smal test application
```python
# InfluxDB
from influxdb_client_3 import InfluxDBClient3, Point

influx_host = "http://192.168.1.144:8086"
influx_org = "orgname"
influx_token = "tokenapi"

client = InfluxDBClient3(url=influx_host, token=influx_token, org=influx_org)

influx_query = '''SELECT * FROM "device_data"'''

# results = client.query_api().query_data_frame('from(bucket: "bucket_test") |> range(start: -1h) |> filter(fn: (r) => r._measurement == "device_data")')
results = client.query(query=influx_query, language='sql', mode='all')
print(results)
```

This produces an error when I try to run it from the VSCode PowerShell inside venv shell:
```txt
python .\test_connect.py    
Traceback (most recent call last):
  File "C:\codetest\portal\test_environment\influxdb\test_connect.py", line 8, in <module>
    client = InfluxDBClient3(url=influx_host, token=influx_token, org=influx_org)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\codetest\portal\venv\Lib\site-packages\influxdb_client_3\__init__.py", line 116, in __init__
    self._client = _InfluxDBClient(
                   ^^^^^^^^^^^^^^^^
TypeError: influxdb_client_3.write_client.client.influxdb_client.InfluxDBClient() got multiple values for keyword argument 'url'
```

**Comment by bednar** [comment]
Hi @lombaardcj,

thanks for using our client.

You have to use `host` keyword instead of `url`:

```python
client = InfluxDBClient3(host=influx_host, token=influx_token, org=influx_org)
```

Best Regards
