### ISSUE TITLE
Unable to query Influxdb

### ISSUE THREAD

**Issue by raphapassini** [InfluxCommunity/influxdb3-python#85]
### Specifications

* Client Version: Influx CLI dev (git: none) build_date: 2023-04-28T14:24:14Z
* InfluxDB Version: v2.7.1 
* Platform: Linux

### Code sample to reproduce problem

```python
from influxdb_client_3 import InfluxDBClient3

# Create a client instance
with open('influxdb_certificate.pem', 'rb') as fp:
    root_cert = fp.read()

token = "my_token"
influxdb_org = "my_org_id"
influxdb_database = "database"
influxdb_host = "{address}"
client = InfluxDBClient3(
    host=influxdb_host, token=token, org=influxdb_org, database=influxdb_database,
    flight_client_options={'tls_root_certs': root_cert})

query = "select * from measurement"
reader = client.query(query=query, language="sql")
table = reader.read_all()
print(table.to_pandas().to_markdown())
```

### Expected behavior

Returned values from the query above

### Actual behavior

```shell
E0426 19:56:38.171490399   59368 hpack_parser.cc:1218]                 Error parsing metadata: error=invalid value key=content-type value=text/html; charset=utf-8
Traceback (most recent call last):
  File "/home/raphael/stuff/eskalator-sample/api/.venv/lib/python3.11/site-packages/influxdb_client_3/__init__.py", line 257, in query
    raise e
  File "/home/raphael/stuff/eskalator-sample/api/.venv/lib/python3.11/site-packages/influxdb_client_3/__init__.py", line 243, in query
    flight_reader = self._flight_client.do_get(ticket, _options)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_flight.pyx", line 1633, in pyarrow._flight.FlightClient.do_get
  File "pyarrow/_flight.pyx", line 58, in pyarrow._flight.check_flight_status
pyarrow._flight.FlightServerError: Flight RPC failed with message: Stream removed. gRPC client debug context: UNKNOWN:Error received from peer ipv4:127.0.1.1:8086 {grpc_message:"Stream removed", grpc_status:2, created_time:"2024-04-26T19:56:38.171564399-03:00"}. Client context: IOError: Server never sent a data message. Detail: Internal```

### Additional info

_No response_

**Comment by bednar** [comment]
Hi @raphapassini,

Thank you for using our client. This client is designed for use with InfluxDB 3. If you need to query InfluxDB 2, please use the [InfluxDB 2 client](https://github.com/influxdata/influxdb-client-python).

Best regards
